apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "100m"
            limits:
              cpu: "250m"
          volumeMounts: # Must be inside the container
            - name: html
              mountPath: /usr/share/nginx/html
      volumes: # Must be inside the spec of the pod template
        - name: html
          configMap:
            name: nginx-index # Name of your ConfigMap
